const BOTON_PRIMARIO = "green";
const HOVER_BOTON_PRIMARIO = "blue";
const BOTON_SECUNDARIO = "white";
const HOVER_BOTON_SECUNDARIO = "lightblue";

export { BOTON_PRIMARIO, HOVER_BOTON_PRIMARIO, BOTON_SECUNDARIO, HOVER_BOTON_SECUNDARIO }