const BOTON_PRIMARIO = "green";
const HOVER_BOTON_PRIMARIO = "blue";
const BOTON_SECUNDARIO = "white";
const HOVER_BOTON_SECUNDARIO = "lightblue";
const WARNING_COLOR = "#F9C74F";
const WARNING_COLOR_HOVER = "white"

export {
    BOTON_PRIMARIO,
    HOVER_BOTON_PRIMARIO,
    BOTON_SECUNDARIO,
    HOVER_BOTON_SECUNDARIO,
    WARNING_COLOR,
    WARNING_COLOR_HOVER
}