const AZUL_PRIMARIO = "#007EA7";
const AZUL_CLARO = "#00A8E8";
const AZUL_OSCURO = "#003459";
const AZUL_PROFUNDO = "#00171F";
const BLANCO = "#FFFFFF";

export {
    AZUL_PRIMARIO,
    AZUL_CLARO,
    AZUL_OSCURO,
    AZUL_PROFUNDO,
    BLANCO
}